branches:
  except:
    - /^\d+\.\d+\.\d+(-\S*)?$/

matrix:
  include:
    - &macos
      os: osx
      osx_image: xcode10
      sudo: required
      language: objective-c
      env:
        - SWIFT_BUILD_OPTION="-Xswiftc -swift-version -Xswiftc 4"

    - <<: *macos
      osx_image: xcode10
      env:
        - SWIFT_BUILD_OPTION="-Xswiftc -swift-version -Xswiftc 4.2"

    - <<: *macos
      osx_image: xcode9.4

    - &linux
      os: linux
      dist: trusty
      sudo: required
      language: ruby
      env:
        - SWIFT_ARCHIVE_URL=https://swift.org/builds/swift-4.2-release/ubuntu1404/swift-4.2-RELEASE/swift-4.2-RELEASE-ubuntu14.04.tar.gz
        - SWIFT_BUILD_OPTION="-Xswiftc -swift-version -Xswiftc 4"
      before_install:
        - curl ${SWIFT_ARCHIVE_URL} -o ../swift.tar.gz
        - mkdir ../swift
        - tar xzf ../swift.tar.gz -C ../swift --strip-components 2
        - export PATH="$(dirname $(pwd))/swift/bin:$PATH"

    - <<: *linux
      env:
        - SWIFT_ARCHIVE_URL=https://swift.org/builds/swift-4.2-release/ubuntu1404/swift-4.2-RELEASE/swift-4.2-RELEASE-ubuntu14.04.tar.gz
        - SWIFT_BUILD_OPTION="-Xswiftc -swift-version -Xswiftc 4.2"

    - <<: *linux
      env:
        - SWIFT_ARCHIVE_URL=https://swift.org/builds/swift-4.1.3-release/ubuntu1404/swift-4.1.3-RELEASE/swift-4.1.3-RELEASE-ubuntu14.04.tar.gz

script:
  - swift build ${SWIFT_BUILD_OPTION}
  - swift build --configuration release ${SWIFT_BUILD_OPTION}
  - swift test ${SWIFT_BUILD_OPTION}
